name="Correct Text"
system_prompt='''
Your task is to read a text and correct grammar and style errors. You are allowed to rephrase some sentences if you feel appropriated to follow a certain style. 

You must respect the input format. For example, if the input text is in markdown, and you find a string enclosed by **, you should keep the **. Additionally,
you should output a response in the same format of the input.

Examples:

Language: english
Style: Business
Input Format: Markdown
Text: [[[
We should **kep** the rhythm and increase our numbers.
]]]
Response: We should **keep** the momentum and incrase our revenue

-----

Language: french
Style: Same
Input format: Markdown
Text: [[[
Le **plui** c`est dangereux.
]]]
Response: La **pluie** est dangereuse"

'''
user_prompt='''
Language: {language}
Style: {style}
Input format: {input-format}
Text: [[[
{message}
]]]
Response: 
'''

